import re
import tldextract
import urllib.parse
import math

SUSPICIOUS_KEYWORDS = [
    'login', 'verify', 'secure', 'update', 'account', 'banking',
    'confirm', 'password', 'credential', 'suspend', 'unusual',
    'signin', 'authenticate', 'validation', 'recover', 'unlock',
    'ebayisapi', 'webscr', 'cmd=', 'dispatch'
]

URL_SHORTENERS = [
    'bit.ly', 'tinyurl.com', 't.co', 'goo.gl', 'ow.ly',
    'buff.ly', 'rebrand.ly', 'cutt.ly', 'shorturl.at', 'is.gd'
]

TRUSTED_DOMAINS = {
    'google', 'youtube', 'facebook', 'twitter', 'instagram',
    'microsoft', 'apple', 'amazon', 'netflix', 'spotify',
    'github', 'linkedin', 'reddit', 'wikipedia', 'stackoverflow',
    'cloudflare', 'zapier', 'notion', 'slack', 'discord',
    'dropbox', 'zoom', 'paypal', 'stripe', 'shopify',
    'twitch', 'pinterest', 'tumblr', 'whatsapp', 'telegram'
}

SUSPICIOUS_TLDS = {
    'tk', 'ml', 'ga', 'cf', 'gq', 'xyz', 'top', 'club',
    'online', 'site', 'work', 'live', 'click', 'link', 'pw'
}

BRAND_NAMES = [
    'paypal', 'google', 'apple', 'microsoft', 'amazon',
    'netflix', 'bank', 'ebay', 'facebook', 'instagram'
]

#using shannon entropy for weird looking domains
def _entropy(s: str) -> float:
    if not s:
        return 0.0
    freq = {}
    for c in s:
        freq[c] = freq.get(c, 0) + 1
    probs = [f / len(s) for f in freq.values()]
    return -sum(p * math.log2(p) for p in probs if p > 0)


def is_trusted(url: str) -> bool:
    ext = tldextract.extract(url)
    return ext.domain.lower() in TRUSTED_DOMAINS


def extract_features(url: str) -> dict:
    parsed   = urllib.parse.urlparse(url)
    ext      = tldextract.extract(url)
    hostname = parsed.netloc or ''
    path     = parsed.path or ''
    params   = parsed.query or ''
    domain   = ext.domain or ''
    suffix   = ext.suffix or ''
    sub      = ext.subdomain or ''
    full_url = url.lower()

    #Length features 
    length_features = {
        'url_length':       len(url),
        'hostname_length':  len(hostname),
        'path_length':      len(path),
        'domain_length':    len(domain),
        'query_length':     len(params),
    }

    # Count features
    count_features = {
        'dot_count':           url.count('.'),
        'hyphen_count':        url.count('-'),
        'hyphens_in_domain':   domain.count('-'),
        'at_sign':             int('@' in url),
        'double_slash':        int('//' in path),
        'question_mark_count': url.count('?'),
        'ampersand_count':     url.count('&'),
        'percent_count':       url.count('%'),
        'param_count':         len(urllib.parse.parse_qs(params)),
        'path_depth':          len([p for p in path.split('/') if p]),
        'subdomain_count':     len(sub.split('.')) if sub else 0,
        'dots_in_domain':      (domain + '.' + suffix).count('.'),
    }

    #Ratio features
    ratio_features = {
        'digit_ratio_url':       sum(c.isdigit() for c in url) / len(url) if url else 0,
        'digit_ratio_domain':    sum(c.isdigit() for c in domain) / len(domain) if domain else 0,
        'letter_ratio_url':      sum(c.isalpha() for c in url) / len(url) if url else 0,
        'special_char_ratio':    sum(not c.isalnum() for c in url) / len(url) if url else 0,
    }

    # Entropy features
    # High entropy in domain = random-looking = generated by attacker
    entropy_features = {
        'domain_entropy':   _entropy(domain),
        'path_entropy':     _entropy(path),
        'url_entropy':      _entropy(url),
    }

    #Boolean flags
    bool_features = {
        'has_https':              int(parsed.scheme == 'https'),
        'has_http':               int(parsed.scheme == 'http'),
        'has_port':               int(bool(parsed.port)),
        'tld_length':             len(suffix),
        'suspicious_tld':         int(suffix in SUSPICIOUS_TLDS),
        'is_trusted_domain':      int(is_trusted(url)),   # ← key new feature
        'is_url_shortener':       int(any(s in hostname for s in URL_SHORTENERS)),

        # IP address instead of domain
        'has_ip_address':         int(bool(re.match(
            r'^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$', hostname
        ))),

        # Brand name in subdomain but NOT the actual domain
        # paypal.fake-login.com → 'paypal' in subdomain, domain is 'fake-login'
        'brand_in_subdomain':     int(
            any(b in sub.lower() for b in BRAND_NAMES) and
            domain.lower() not in TRUSTED_DOMAINS
        ),

        # Suspicious keyword in URL
        'has_suspicious_keyword': int(any(k in full_url for k in SUSPICIOUS_KEYWORDS)),

        # HTTPS doesn't mean safe — phishers use it too
        'https_with_keyword':     int(
            parsed.scheme == 'https' and
            any(k in full_url for k in SUSPICIOUS_KEYWORDS)
        ),

        # Hex encoding in path — often used to obfuscate
        'has_hex_encoding':       int(bool(re.search(r'%[0-9a-fA-F]{2}', path))),

        # Punycode — used to make foreign chars look like latin
        'has_punycode':           int('xn--' in hostname.lower()),

        # Multiple redirects encoded in URL
        'has_redirect':           int('redirect' in full_url or 'url=' in full_url),

        # Domain looks like IP with dashes — 192-168-1-1.evil.com
        'ip_like_domain':         int(bool(re.match(r'^\d+-\d+-\d+-\d+', domain))),
    }

    return {
        **length_features,
        **count_features,
        **ratio_features,
        **entropy_features,
        **bool_features,
    }